messages:
  reload: "&aPlugin &6PickLock &abyl úspěšně reloadnut."
  unknown-cmd: "&cNeznámý příkaz."
  error: "&cNiečo je špatně..."
  ussage: "&6Použití: &7"
  unknown-key: "&cNeznámý typ klíče."
  no-permission: "&cNa toto nemáš oprávnenie."
  finish-previos-action: "&6Dokonči akciu z predchadzajúceho príkazu." 
  console-cannot-do-that: "&cKonzole tohle nezvládne."
  get-key: "&aPrávě si získal &6klíč&a."
  get-hook: "&aPrávě si získal &6šperhák&a."
  on-unlock: "&aOdemknul jsi."
  on-lock: "&aZamknul jsi."
  wrong-key: "&cKlíč nepasuje do klíčové dírky."
  key-is-used: "&cKlíč byl již použit."
  on-first-lock: "&aÚspešně jsi zamknul."
  is-locked: "&cJe zamčeno."
  is-not-locked: "&cJe zamčeno."
  no-lock: "&cTruhla/dveře na které jsi kliknul nejsou zamknuté."
  on-brake-with-lock: "&cNemůžeš zničit zamčenou truhlu/dveře."
  to-remove-lock: "&eKlini pravým tlačítkem na odstranění zámku."  
  remove-lock: "&aZámek byl úspěšně odstraněný."
  remove-lock-not-owned: "&cNemůžeš odstranit zámek, který ti nepatří"
  to-lock-info: "&eKlikni pravým tlačítkem na zámek pro více informací."
  need-to-hold-key: "&cMusíš v ruke držať kľúč."
  to-lock: "&eKlikni pravým tlačítkem na zámek pro zamknutí."
  to-unlock: "&eKlikni pravým tlačítkem na zámek pro odemknutí."
  cannot-be-placed-door: "&cSem to nemôžeš položiť."
  cannot-be-placed-chest: "&cNie je možné spraviť dvojtruhlu z truhly zo zámkom."
  bad-pin: "&cZlá západka."
  on-hook-broke: "&cZlomil si šperhák."
  on-lockpick: "&aÚspešne si lockpickol zámok."
 
lockpicking:
  hook-gui:
    inventory-title: "&8&lLockpick"
    tutorial-item-title: "&aNávod"
    pin-item-title: "&9Západka"
    lore:
      - "  "
      - "&bPosuň západky v správnom"
      - "&bporadí pre otvorenie zámku."
  options:
    levels: 150
    base-lockpick-chance: 97
    lockpick-pin-multipler: 1.05
    lockpick-level-multipler: 0.995
    base-succes-xp: 1.5
    xp-level-multipler: 1.015
    xp-pin-multipler: 1.05
  
keys:
  basic:
    material: STICK
    type: basic
    name: "&aBronzový klíč"    
    pick-difficulty: 3
    customModelData: 2810101
  advanced:
    material: STICK
    type: advanced
    name: "&6Stříbrný klíč"    
    pick-difficulty: 6
    customModelData: 2810102
  pro:
    material: STICK
    type: pro
    name: "&cDiamantový klíč"    
    pick-difficulty: 8
    customModelData: 2810103

hooks:
  basic:
    material: STICK
    type: basic
    name: "&9Šperhák"
    customModelData: 2810201
  
locking:
  chests:
    - CHEST
    - TRAPPED_CHEST
  doors:
    - OAK_DOOR
    - BIRCH_DOOR
    - CRIMSON_DOOR
    - DARK_OAK_DOOR
    - JUNGLE_DOOR
    - SPRUCE_DOOR
    - WARPED_DOOR
    - IRON_DOOR
  trapdoors:
    - OAK_TRAPDOOR
    - ACACIA_TRAPDOOR
    - BIRCH_TRAPDOOR
    - CRIMSON_TRAPDOOR
    - DARK_OAK_TRAPDOOR
    - JUNGLE_TRAPDOOR
    - SPRUCE_TRAPDOOR
    - WARPED_TRAPDOOR
    - IRON_TRAPDOOR